
###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

about:
  descriptionUrl: https://github.com/pigeonposse/.github/tree/main/profile
  descriptionLong: PigeonPosse is a ✨ code development collective ✨ focused on creating practical and interesting tools that help developers and users enjoy a more agile and comfortable experience. Our projects cover various programming sectors and we do not have a thematic limitation in terms of projects.

funding: 
  - kofi: 
      url: "https://ko-fi.com/pigeonposse"
      iframe: '<iframe id="kofiframe" loading="lazy" src="https://ko-fi.com/pigeonposse/?hidefeed=true&amp;widget=true&amp;embed=true&amp;preview=true" ></iframe>'
  - github: 
      url: "https://github.com/sponsors/pigeonposse/dashboard"
  - web: 
      url: "{{orgData.blog}}?popup=donate"
  
social:
  - twiiter: "https://twitter.com/pigeonposse_"
  - instgram: "https://www.instagram.com/pigeon.posse/"
  - email: "{{orgData.email}}"


###############################################################################
